### PR TITLE
remove static call to Tiqr_Response_Abstract::createResponse()

### PR DESCRIPTION
**Pull request by joostd**
Non-static method Tiqr_Response_Abstract::createResponse() should not be called statically

### CODE REVIEW

**Comment by lineke** [comment]
Are you sure this is the right implementation? Why not make the nonstatic method static? I think the reason the createResponse method exists is to support newer versions in the future.

**Comment by joostd** [comment]
Maybe consult with the original author?

**Comment by lineke** [comment]
@ijansch What do you think?

**Comment by ijansch** [comment]
Yes, createResponse could be a static abstract factory But its not aware of the version so Joost's fix is the correct one now.

**Pull request merged**
